from Chapter2_The_Queue.ch2_01_queue_class import Queue

my_q = Queue()
my_q.enqueue('a')
print(my_q.items)
my_q.enqueue('b')
print(my_q.items)
print(my_q.dequeue())
my_q.enqueue('2')
my_q.enqueue(3)
print(my_q.items)
print(my_q.peek())
print(my_q.size())
print(my_q.is_empty())
print(my_q.dequeue())
print(my_q.dequeue())
print(my_q.dequeue())
print(my_q.dequeue())
print(my_q.peek())
print(my_q.size())
print(my_q.is_empty())
